baseURL = "https://l3sota.github.io/"
defaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "en-us,ja-jp"
title = "L3Sota"
theme = "smol"

[params]
  subtitle = "Welcome to my infrequently updated website!"
  dateFmt = "2006-01-02T15:04:05Z"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ja]
    languageName = "日本語"
    weight = 2

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

    [[menu.footer]]
    name = "Github"
    url = "https://github.com/L3Sota"
    weight = 1

    [[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/L3Sota"
    weight = 2

    [[menu.footer]]
    name = "Keybase"
    url = "https://keybase.io/l3sota"
    weight = 3
