name: Build and Host
on:
  push:
    branches:
      - main
      - feat/github-actions
    paths:
      - archetypes/**
      - config.toml
      - content/**
      - data/**
      - themes/**

jobs:
  build_and_host:
    runs-on: ubuntu-latest
    name: Build site and push to publish branch for hosting on Github Pages
    timeout-minutes: 5
    steps:
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout publish
        uses: actions/checkout@v2
        with:
          ref: publish
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main
          submodules: true
      - name: Reset publish to main
        run: |
          git config --global --add user.name github-actions
          git config --global --add user.email github-actions@github.com
          git checkout publish
          git reset --hard main
      - name: Clean output dir (usually fails since public shouldn't exist)
        continue-on-error: true
        run: rm -rf public/
      - name: 💡 Build!
        run: hugo
      - name: Move newly built site to repo root
        run: git rm -rf '*' && mv -f public/* ./
      - name: Commit changes (can fail if no changes)
        id: commit
        continue-on-error: true
        run: git add . && git commit -m "Host site from $GITHUB_SHA"
      - name: Force push to origin if commit succeeded
        if: steps.commit.outcome == 'success'
        run: git push -f origin HEAD:publish
