name: Build and Host
on:
  pull_request:
    branches: [develop]
    types: [closed]
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - '**.hbs'

jobs:
  build_and_host:
    runs-on: ubuntu-latest
    name: Build site and push to master for hosting on Github Pages
    timeout-minutes: 5
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
      - name: Run npm ci, build site
        run: |
          npm ci
          npx @11ty/eleventy
      - name: Checkout master
        run: |
          mkdir -p ~/.config/git
          cat .gitignore >> ~/.config/git/ignore
          git config --global --add core.excludesFile ~/.config/git/ignore
          git config --global --add user.name 'L3Sota'
          git config --global --add user.email 'l3sota@protonmail.com'
          git fetch --no-tags --prune --depth=1 origin master
          git checkout -b master -t origin/master
      - name: Remove existing site (can fail if repo is empty)
        continue-on-error: true
        run: git rm -r .
      - name: Move newly built site to top level
        run: mv -f _site/* ./ && rmdir _site
      - name: Commit changes (can fail if no changes)
        id: commit
        continue-on-error: true
        run: git add . && git commit -m 'Host site from merge ${{ github.head_ref }} → ${{ github.base_ref }}'
      - name: Push to origin if commit succeeded
        if: steps.commit.outcome == 'success'
        run: git push origin HEAD:origin/master
