name: Build and Host
on: [push]

jobs:
  build_and_host:
    runs-on: ubuntu-latest
    name: Build site and push to master for hosting on Github Pages
    timeout-minutes: 5
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
      - name: Run npm ci, build site
        run: |
          npm ci
          npx @11ty/eleventy
      - name: Commit to master, push to origin
        run: |
          mkdir -p ~/.config/git
          cat .gitignore >> ~/.config/git/ignore
          git config --global --add core.excludesFile ~/.config/git/ignore
          git config --global --add user.name 'L3Sota'
          git config --global --add user.email 'l3sota@protonmail.com'
          git fetch --no-tags --prune --depth=1 origin master
          git checkout -b master -t origin/master
          mv -f _site/* ./
          rmdir _site
          git add '**.html' '**.css' '**.js'
          git commit -a -m 'Host site from merge ${{ github.head_ref }} → ${{ github.base_ref }}'
          git push origin HEAD
